name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_ARCH: aarch64
  QEMU_STATIC_VERSION: v5.1.0-7
  DOCKER_CONTAINER: ubi-multiarch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
            docker run --rm --privileged multiarch/qemu-user-static:register --reset
            ./build.sh -a "$env:DOCKER_ARCH" -c "$env:DOCKER_CONTAINER" -v latest -q "$env:QEMU_STATIC_VERSION"
