name: Release

on:
  push:
    tags:
      - 'v*'
  
  workflow_dispatch:

env:
  DOCKER_ARCH: aarch64
  QEMU_STATIC_VERSION: v5.1.0-7
  DOCKER_REPO: quay.io/qiotproject
  DOCKER_CONTAINER: ubi-multiarch


jobs:
  create_and_publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: ""
          draft: false
          prerelease: false

      - name: Build the Docker image
        run: |
            docker run --rm --privileged multiarch/qemu-user-static:register --reset
            ./build.sh -a "$DOCKER_ARCH" -c "$DOCKER_CONTAINER" -v ${{ steps.get_version.outputs.VERSION }} -q "$QEMU_STATIC_VERSION" 

      - name: Push To Quay
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v1
        with:
          image: ${{ env.DOCKER_CONTAINER }}
          tag: ${{ steps.get_version.outputs.VERSION }}
          registry: ${{ env.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
