name: Nightly Build (from Develop branch)

on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * *'
  
  push:
    paths-ignore:
      - .github/workflows/**
      - .gitignore
      - LICENSE
      - README.md
      - release.sh
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Load environment variables from .env files 
        uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: variables.env
        
      - name: Test imported environment variables ARCH
        shell: bash
        run: |
          echo "PROJECT_VERSION: $PROJECT_VERSION"
          echo "DOCKER_ARCH: $DOCKER_ARCH"
          echo "QEMU_STATIC_VERSION: $QEMU_STATIC_VERSION"
          echo "DOCKER_CONTAINER: $DOCKER_CONTAINER"
          echo "UBI_IMAGE_VERSION: $UBI_IMAGE_VERSION"

      - name: Build the Docker image
        run: |
            docker run --rm --privileged multiarch/qemu-user-static:register --reset
            ./build.sh -u "$UBI_IMAGE_VERSION" -a "$DOCKER_ARCH" -c "$DOCKER_CONTAINER" -v "$PROJECT_VERSION" -q "$QEMU_STATIC_VERSION"
